cpansec-minutes-2024-03-13.md: update meeting minutes
CPAN-Security/security.metacpan.org pull request #55
Opened 2024-03-15 00:59 UTC by timlegge

@ingydotnet  @perlpunk you are not on the reviewers list but if you have any issues let me know

2024-03-15 01:51 UTC, oalders approved these changes

2024-03-15 07:16 UTC, sjn commented on docs/minutes/cpansec-minutes-2024-03-13.md
> +    - @stigtsp - Public facing Vulnerability Index. - possibly chat at PTC`
s/PTC/PTS/

2024-03-15 07:19 UTC, sjn commented on docs/minutes/cpansec-minutes-2024-03-13.md
> +- stigtsp and timlegge are working on the old vulnerabilities to have CVEs issued as required
Would it be meaningful to specify where these old vulnerabilities are found?

2024-03-15 07:21 UTC, sjn requested changes
Typo fix needed, and (optionally) check of the source of vulnerabilities that is being reviewed.

2024-03-15 18:19 UTC, garu approved these changes
aside from s/PTC/PTS/ the rest is as I remember it. Great work, @timlegge!

2024-03-16 03:33 UTC, sjn approved these changes
LGTM

2024-03-16 03:34 UTC, merged