Minutes for 2024-04-10 meeting
CPAN-Security/security.metacpan.org pull request #60
Opened 2024-04-14 18:25 UTC by sjn

2024-04-15 01:03 UTC, timlegge approved these changes
Lgtm

2024-04-16 13:02 UTC, oalders requested changes

2024-04-16 13:02 UTC, oalders commented on docs/minutes/cpansec-minutes-2024-04-10.md
> +    *   @oalders – had a meeting with TPRF on this. No progress.
The meeting wasn't about this and it didn't really come up, so I'd rather not have it in the notes.

2024-04-16 17:39 UTC, oalders approved these changes

2024-04-19 04:11 UTC, merged